### ISSUE TITLE
Create algorithms to compare the networks

### ISSUE THREAD

**Issue by davide-f** [pypsa-meets-earth/network-comparison#2]
There is the need to create algorithms to successfully make two networks (N1 and N2) comparable.

Each algorithm can be seen as a function A that takes in input N1&N2 and in outputs two mapped networks N1p and N2p that are comparable.

The comparability stands in the fect that the networks N1p and N2p shall have the name of the buses that match, hence:
n1p.buses.index (=/equivalent) n2p.buses.index

**Comment by GbotemiB** [comment]
Happy to contribute here 👍🏼. Maybe with some help from Jess, I think she has more experience here 🙃

**Comment by jessLryan** [comment]
Absolutely happy to help :-)
